#ifndef LOCATER_CONFIG_H
#define LOCATER_CONFIG_H

#include <stdint.h>

#define LOCATER_PROJECT_NAME              "R1_LocaterV2"

#define LOCATER_ENCODER_PPR               1024U
#define LOCATER_TASK_PERIOD_MS            10U
#define LOCATER_TELEMETRY_PERIOD_MS       20U
#define LOCATER_USART1_BOOT_TEST_ENABLE   0U
#define LOCATER_TELEMETRY_DIAG_ENABLE     0U
#define LOCATER_SERIAL_DEBUG_FANOUT       0U

#define LOCATER_ENCODER_X_REVERSED        0U
#define LOCATER_ENCODER_Y_REVERSED        0U

#define LOCATER_PI                        3.14159265358979323846f
#define LOCATER_INV_SQRT2                 0.70710678118f

#define LOCATER_ENCODER_NOISE_THRESHOLD   1
#define LOCATER_ENCODER_SCALE_P_MM        0.00771069429f
#define LOCATER_ENCODER_SCALE_Q_MM        0.00771069429f
#define LOCATER_ENCODER_OFFSET_ANGLE_DEG  225.0f
#define LOCATER_ENCODER_OFFSET_L_MM       268.16f
#define LOCATER_ENCODER_CROSS_P_FROM_Q    0.0f
#define LOCATER_ENCODER_CROSS_Q_FROM_P    0.0f
#define LOCATER_ENCODER_ROT_COMP_GAIN     0.100f
#define LOCATER_ENCODER_POS_X_CORR        (-1.035f)
#define LOCATER_ENCODER_POS_Y_CORR        (-1.0366f)

#define LOCATER_INITIAL_X_CM              0.0f
#define LOCATER_INITIAL_Y_CM              0.0f
#define LOCATER_INITIAL_YAW_DEG           0.0f

#define LOCATER_H30_YAW_OFFSET_DEG        -100.3f
#define LOCATER_H30_ACCEL_X_BIAS_MPS2     0.0f
#define LOCATER_H30_ACCEL_Y_BIAS_MPS2     0.0f
#define LOCATER_H30_ACCEL_X_SCALE         1.0f
#define LOCATER_H30_ACCEL_Y_SCALE         1.0f
#define LOCATER_H30_ACCEL_X_REVERSED      0U
#define LOCATER_H30_ACCEL_Y_REVERSED      0U
#define LOCATER_H30_ACCEL_DEADBAND_MPS2   0.05f
#define LOCATER_H30_VELOCITY_DECAY_PER_S  0.30f
#define LOCATER_H30_MAX_INTEGRATE_DT_MS   100U

#define LOCATER_LIDAR_OFFSET_X_CM         (-42.2f)
#define LOCATER_LIDAR_OFFSET_Y_CM         0.5f
#define LOCATER_LIDAR_YAW_OFFSET_DEG      0.0f
#define LOCATER_LIDAR_ONLINE_TIMEOUT_MS   300U

#define LOCATER_HOST_FRAME_FLOAT_COUNT     11U
#define LOCATER_HOST_FRAME_LEN             (2U + LOCATER_HOST_FRAME_FLOAT_COUNT * 4U + 1U)

#define LOCATER_HOST_START_SIDE_RED        0U
#define LOCATER_HOST_START_SIDE_BLUE       1U
#define LOCATER_HOST_START_SIDE            LOCATER_HOST_START_SIDE_RED

#define LOCATER_HOST_RED_START_X_CM        (-552.5f)
#define LOCATER_HOST_RED_START_Y_CM        550.0f
#define LOCATER_HOST_RED_START_YAW_DEG     0.0f

#define LOCATER_HOST_BLUE_START_X_CM       552.5f
#define LOCATER_HOST_BLUE_START_Y_CM       550.0f
#define LOCATER_HOST_BLUE_START_YAW_DEG    180.0f

#define LOCATER_HOST_OFFSET_LOCAL_ODOM     1U

#define LOCATER_USART1_BAUDRATE           115200U
#define LOCATER_USART2_BAUDRATE           1152000U
#define LOCATER_H30_IMU_BAUDRATE          460800U
#define LOCATER_USART3_BAUDRATE           115200U
#define LOCATER_UART4_BAUDRATE            460800U
#define LOCATER_UART5_BAUDRATE            115200U

#define LOCATER_DT35_SENSOR_1_ID          0x01U
#define LOCATER_DT35_SENSOR_2_ID          0x02U
#define LOCATER_DT35_SENSOR_1_NAME        "DT35-1(-X Left)"
#define LOCATER_DT35_SENSOR_2_NAME        "DT35-2(+X Right)"
#define LOCATER_DT35_SENSOR_1_SCALE       0.0006123656f
#define LOCATER_DT35_SENSOR_1_OFFSET_M    (-2.2454257f)
#define LOCATER_DT35_SENSOR_2_SCALE       0.0006141103f
#define LOCATER_DT35_SENSOR_2_OFFSET_M    (-2.2616548f)
#define LOCATER_DT35_MIN_DISTANCE_MM      200.0f
#define LOCATER_DT35_MAX_DISTANCE_MM      10000.0f
#define LOCATER_DT35_MAX_CONSECUTIVE_ERRORS 5U
#define LOCATER_DT35_UART_RX_DRAIN_LIMIT  16U
#define LOCATER_DT35_UART_TX_TIMEOUT_MS   10U
#define LOCATER_DT35_UART_RX_TIMEOUT_MS   35U
#define LOCATER_DT35_UART_BYTE_TIMEOUT_MS 2U
#define LOCATER_DT35_READ_RETRY_COUNT     2U
#define LOCATER_DT35_FALLBACK_SCAN_ENABLE 1U
#define LOCATER_DT35_SCAN_MIN_ID          0x01U
#define LOCATER_DT35_SCAN_MAX_ID          0x0FU
#define LOCATER_DT35_TASK_PERIOD_MS       25U
#define LOCATER_DT35_STARTUP_DELAY_MS     1000U
#define LOCATER_DT35_ONLY_SENSOR_2_TEST   0U

#endif /* LOCATER_CONFIG_H */
