#ifndef LOCATER_CONFIG_H
#define LOCATER_CONFIG_H

#include <stdint.h>

#define LOCATER_PROJECT_NAME              "R1_LocaterV2"

#define LOCATER_ENCODER_PPR               1024U
#define LOCATER_TASK_PERIOD_MS            10U
#define LOCATER_TELEMETRY_PERIOD_MS       20U
#define LOCATER_USART1_BOOT_TEST_ENABLE   0U
#define LOCATER_TELEMETRY_H30_DIAG_ENABLE 0U
#define LOCATER_SERIAL_DEBUG_FANOUT       0U

#define LOCATER_ENCODER_X_REVERSED        0U
#define LOCATER_ENCODER_Y_REVERSED        0U

#define LOCATER_PI                        3.14159265358979323846f
#define LOCATER_INV_SQRT2                 0.70710678118f

#define LOCATER_ENCODER_NOISE_THRESHOLD   1
#define LOCATER_ENCODER_SCALE_P_MM        0.00771069429f
#define LOCATER_ENCODER_SCALE_Q_MM        0.00771069429f
#define LOCATER_ENCODER_OFFSET_ANGLE_DEG  225.0f
#define LOCATER_ENCODER_OFFSET_L_MM       268.16f
#define LOCATER_ENCODER_CROSS_P_FROM_Q    0.0f
#define LOCATER_ENCODER_CROSS_Q_FROM_P    0.0f
#define LOCATER_ENCODER_ROT_COMP_GAIN     0.100f
#define LOCATER_ENCODER_POS_X_CORR        (-1.035f)
#define LOCATER_ENCODER_POS_Y_CORR        (-1.0366f)

#define LOCATER_INITIAL_X_CM              0.0f
#define LOCATER_INITIAL_Y_CM              0.0f
#define LOCATER_INITIAL_YAW_DEG           0.0f

#define LOCATER_H30_YAW_OFFSET_DEG        -100.3f
#define LOCATER_H30_ACCEL_X_BIAS_MPS2     0.0f
#define LOCATER_H30_ACCEL_Y_BIAS_MPS2     0.0f
#define LOCATER_H30_ACCEL_X_SCALE         1.0f
#define LOCATER_H30_ACCEL_Y_SCALE         1.0f
#define LOCATER_H30_ACCEL_X_REVERSED      0U
#define LOCATER_H30_ACCEL_Y_REVERSED      0U
#define LOCATER_H30_ACCEL_DEADBAND_MPS2   0.05f
#define LOCATER_H30_VELOCITY_DECAY_PER_S  0.30f
#define LOCATER_H30_MAX_INTEGRATE_DT_MS   100U

#define LOCATER_USART1_BAUDRATE           115200U
#define LOCATER_USART2_BAUDRATE           460800U
#define LOCATER_H30_IMU_BAUDRATE          460800U
#define LOCATER_USART3_BAUDRATE           460800U
#define LOCATER_UART4_BAUDRATE            460800U

#endif /* LOCATER_CONFIG_H */
